# Any hooks failure (except pytest and flake8) means that
# the problem is resolved and you should
# re-stage and re-commit the changes.
repos:

#   Formatting

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.7.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        name: 'format according to pep8'
        types: [python]
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.7.6
    hooks:
    -   id: autoflake
        name: 'fix common linting issues'
        types: [python]
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
    -   id: docformatter
        name: 'format docstrings'
        types: [python]
-   repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
    -   id: unify
        name: 'enforce single quotes'
        types: [python]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        name: 'modernize the code'
        args: [--py310-plus]
        types: [python]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
    -   id: add-trailing-comma
        name: 'add trailing commas'
        args: [--py36-plus]
        types: [python]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.5
    hooks:
    -   id: reorder-python-imports
        name: 'reorder python imports'
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

### Heavyweigth, should be run standalone
# -   repo: https://github.com/PyCQA/prospector
#     rev: 1.7.5
#     hooks:
#     -   id: prospector

#   Linter checks and WeMake styleguide enforcement

-   repo: local
    hooks:
    # If flake fails, you should fix the problems manually.
    -   id: flake8
        name: 'check styling consistency: we-make-styleguide'
        entry: flake8
        language:  system
        pass_filenames: true
        types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'
    hooks:
    -   id: mypy
        name: 'check static typing consistency'
        args: [--no-strict-optional, --ignore-missing-imports]
        types: [python]
-   repo: https://github.com/python-poetry/poetry
    rev: '1.2'
    hooks:
    -   id: poetry-check
        name: 'check pyproject.toml'
    -   id: poetry-lock
        name: 'resolve dependencies and write a .lock file'
        args: ["--no-update"]
    -   id: poetry-export
        alias: poetry-export-run
        name: 'export run dependencies to requirements.txt'
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
    -   id: poetry-export
        alias: poetry-export-dev
        name: 'export dev dependencies to dev-requirements.txt'
        args: ["-f", "requirements.txt", "-o", "dev-requirements.txt", "--without-hashes", "--with=dev"]

# #   Tests
#
# ## Disabled until tests are green
# -   repo: local
#     hooks:
#     -   id: pytest-check
#         name: 'run network-independent tests'
#         entry: pytest
#         language: system
#         pass_filenames: false
#         always_run: true
