# This file can be modified at any time by the project lead
# without any notices. And it is not ever a breaking change.
# This file is included into wemake-preset.

["setup.cfg".flake8]
format = "wemake"
show-source = true

# Plugins:
max-line-length = 80
max-complexity = 6

# darglint:
docstring-style = "python"

# Violations:
show-violation-links = True

["setup.cfg".isort]
profile = "wemake"
